drop table if exists wm_material_stock_log;
CREATE TABLE `wm_material_stock_log` (
                                         `log_id` bigint NOT NULL AUTO_INCREMENT COMMENT '日志ID',
                                         `material_stock_id` bigint NOT NULL COMMENT '关联库存ID',
                                         `item_id` bigint NOT NULL COMMENT '物料ID',
                                         `item_code` varchar(64) DEFAULT NULL COMMENT '产品物料编码',
                                         `item_name` varchar(255) DEFAULT NULL COMMENT '产品物料名称',
                                         `change_type` tinyint NOT NULL COMMENT '变化类型（10:入库, 20:出库, 30:盘点等）',
                                         `before_quantity` double(12,2) DEFAULT NULL COMMENT '变化前库存数量',
                                         `after_quantity` double(12,2) DEFAULT NULL COMMENT '变化后库存数量',
                                         `change_quantity` double(12,2) DEFAULT NULL COMMENT '库存变化数量',
                                         `source_doc_id` bigint DEFAULT NULL COMMENT '被消耗单据ID',
                                         `source_doc_code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '被消耗单据编号',
                                         `source_doc_name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '被消耗单据名称',
                                         `source_doc_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '被消耗单据类型',
                                         `workorder_id` bigint DEFAULT NULL COMMENT '生产工单ID',
                                         `workorder_code` varchar(64) DEFAULT NULL COMMENT '生产工单编号',
                                         `workorder_name` varchar(255) DEFAULT NULL COMMENT '生产工单名称',
                                         `operation_user_id` bigint DEFAULT NULL COMMENT '操作人ID',
                                         `operation_by` varchar(64) DEFAULT '' COMMENT '操作人姓名',
                                         `operation_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '操作时间',
                                         `description` varchar(500) DEFAULT NULL COMMENT '变化描述',
                                         `create_user_id` bigint DEFAULT NULL COMMENT '创建人ID',
                                         `create_by` varchar(64) DEFAULT '' COMMENT '创建人',
                                         `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                         `update_user_id` bigint DEFAULT NULL COMMENT '更新人ID',
                                         `update_by` varchar(64) DEFAULT '' COMMENT '更新人',
                                         `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                         `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                         `deleted` int DEFAULT '0' COMMENT '逻辑删除字段 0:未删除 1:已删除',
                                         `deleteAt` datetime DEFAULT '1000-01-01 00:00:00' COMMENT '逻辑删除辅助字段',
                                         `version` int DEFAULT '1' COMMENT '乐观锁',
                                         `source_line_id` bigint DEFAULT NULL COMMENT '被消耗单据行ID',
                                         PRIMARY KEY (`log_id`),
                                         KEY `idx_item_id` (`item_id`),
                                         KEY `idx_workorder_id` (`workorder_id`),
                                         KEY `idx_change_type` (`change_type`),
                                         KEY `idx_operation_time` (`operation_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='库存变化日志表';

drop table if exists wm_log_failure;
CREATE TABLE `wm_log_failure` (
                                  `failure_id` bigint NOT NULL AUTO_INCREMENT COMMENT '失败记录ID',
                                  `log_id` bigint DEFAULT NULL COMMENT '原始日志ID（若有）',
                                  `material_stock_id` bigint NOT NULL COMMENT '关联库存ID',
                                  `failure_reason` varchar(500) DEFAULT NULL COMMENT '日志写入失败原因',
                                  `failure_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '失败时间',
                                  `log_data` text COMMENT '失败时的原始日志数据',
                                  `create_user_id` bigint DEFAULT NULL COMMENT '创建人ID',
                                  `create_by` varchar(64) DEFAULT '' COMMENT '创建人',
                                  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
                                  `update_user_id` bigint DEFAULT NULL COMMENT '更新人ID',
                                  `update_by` varchar(64) DEFAULT '' COMMENT '更新人',
                                  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
                                  `remark` varchar(500) DEFAULT NULL COMMENT '备注',
                                  `deleted` int DEFAULT '0' COMMENT '逻辑删除字段 0:未删除 1:已删除',
                                  `deleteAt` datetime DEFAULT '1000-01-01 00:00:00' COMMENT '逻辑删除辅助字段',
                                  `version` int DEFAULT '1' COMMENT '乐观锁',
                                  PRIMARY KEY (`failure_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='日志写入失败记录表';

