SHOW CREATE TABLE tran_order;
SHOW CREATE TABLE tran_order_line;

CREATE TABLE `tran_order` (
  `tran_order_id` bigint(20) NOT NULL COMMENT '送货单id',
  `tran_order_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '订单编码',
  `warehouse_id` bigint(20) DEFAULT NULL COMMENT '仓库id',
  `warehouse_name` varchar(255) DEFAULT NULL COMMENT '仓库名称',
  `tran_order_type` varchar(64) DEFAULT NULL COMMENT '送货类别',
  `status` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'PREPARE' COMMENT '状态',
  `client_id` bigint(20) NOT NULL COMMENT '客户id',
  `client_code` varchar(64) DEFAULT NULL COMMENT '客户编码',
  `client_name` varchar(255) NOT NULL COMMENT '客户名称',
  `tran_date` datetime NOT NULL COMMENT '送货日期',
  `address` varchar(255) DEFAULT NULL COMMENT '送货地址',
  `total_amount` decimal(12,2) unsigned DEFAULT '0.00' COMMENT '总金额',
  `weight` decimal(11,2) unsigned DEFAULT '0.00' COMMENT '总重量',
  `tolal` int(11) unsigned DEFAULT '0' COMMENT '总件数',
  `currency` varchar(64) DEFAULT NULL COMMENT '币别',
  `pay_up` varchar(64) DEFAULT NULL COMMENT '结账方式',
  `follower_man` varchar(64) DEFAULT NULL COMMENT '跟单',
  `bus_man` varchar(64) DEFAULT NULL COMMENT '业务员',
  `attr1` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '预留字段1',
  `attr2` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '预留字段2',
  `attr3` int(11) DEFAULT '0' COMMENT '预留字段3',
  `attr4` int(11) DEFAULT '0' COMMENT '预留字段4',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人id',
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '备注',
  PRIMARY KEY (`tran_order_id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售送货单'

CREATE TABLE `tran_order_line` (
  `tran_order_line_id` bigint(20) NOT NULL COMMENT 'id',
  `tran_order_id` bigint(20) NOT NULL COMMENT '送货单id',
  `client_id` bigint(20) NOT NULL COMMENT '客户id',
  `client_code` varchar(64) DEFAULT NULL COMMENT '客户编码',
  `client_name` varchar(255) NOT NULL COMMENT '客户名称',
  `follower_man` varchar(64) DEFAULT NULL COMMENT '跟单',
  `bus_man` varchar(64) DEFAULT NULL COMMENT '业务员',
  `tran_order_type` varchar(64) DEFAULT NULL COMMENT '送货类别',
  `tran_date` datetime NOT NULL COMMENT '送货日期',
  `tran_code` varchar(64) DEFAULT NULL COMMENT '送货单号',
  `warehouse_id` bigint(20) DEFAULT NULL COMMENT '仓库id',
  `warehouse_code` varchar(64) DEFAULT NULL COMMENT '仓库编码',
  `warehouse_name` varchar(255) DEFAULT NULL COMMENT '仓库名称',
  `sales_order_id` bigint(20) NOT NULL COMMENT '销售订单id',
  `sales_order_code` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '销售订单编码',
  `product_id` bigint(20) NOT NULL COMMENT '产品id',
  `product_code` varchar(64) NOT NULL COMMENT '产品编码',
  `product_name` varchar(64) NOT NULL COMMENT '产品名称',
  `product_spec` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT NULL COMMENT '产品规格',
  `quality` varchar(64) DEFAULT NULL COMMENT '材质',
  `level` varchar(64) DEFAULT NULL COMMENT '质量等级',
  `color_name` varchar(255) NOT NULL COMMENT '颜色',
  `unit_of_measure` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL COMMENT '单位',
  `sale_qty` decimal(11,2) DEFAULT NULL COMMENT '出货数',
  `sale_thqty` decimal(11,2) DEFAULT NULL COMMENT '备品数',
  `amount` decimal(12,2) NOT NULL DEFAULT '0.00' COMMENT '单价',
  `total_amount` decimal(12,2) DEFAULT NULL COMMENT '金额',
  `sale_sgqty` decimal(11,2) DEFAULT NULL COMMENT '手工消数',
  `weight` decimal(11,2) DEFAULT NULL COMMENT '重量',
  `tax` int(11) DEFAULT NULL COMMENT '含税',
  `extra` decimal(12,4) DEFAULT NULL COMMENT '附加费',
  `remark` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '备注',
  `pic_num` int(11) DEFAULT NULL COMMENT '件数',
  `po` varchar(32) DEFAULT NULL COMMENT 'po',
  `sku` varchar(32) DEFAULT NULL COMMENT 'sku',
  `client_spec` varchar(500) DEFAULT NULL COMMENT '客户规格',
  `client_product_name` varchar(64) DEFAULT NULL COMMENT '客户品名',
  `client_color` varchar(64) DEFAULT NULL COMMENT '客户颜色',
  `workorder_id` bigint(20) DEFAULT NULL COMMENT '工单ID',
  `workorder_code` varchar(64) DEFAULT NULL COMMENT '生产工单编码',
  `status` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT 'PREPARE' COMMENT '状态',
  `create_user_id` bigint(20) DEFAULT NULL COMMENT '创建人id',
  `create_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime DEFAULT NULL COMMENT '创建时间',
  `update_user_id` bigint(20) DEFAULT NULL COMMENT '更新人id',
  `update_by` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='销售送货单列表'