SET FOREIGN_KEY_CHECKS = 0;

TRUNCATE TABLE sys_logininfor;
TRUNCATE TABLE wm_transaction;
TRUNCATE TABLE pro_task;
TRUNCATE TABLE pro_feedback;
TRUNCATE TABLE wm_material_stock;
TRUNCATE TABLE pro_client_order_item;
TRUNCATE TABLE pro_workorder_bom;
TRUNCATE TABLE wm_item_consume;
TRUNCATE TABLE wm_rt_issue;
TRUNCATE TABLE wm_waste_header;
TRUNCATE TABLE md_item;
TRUNCATE TABLE md_product_bom;
TRUNCATE TABLE pro_route_process;
TRUNCATE TABLE wm_rt_issue_line;
TRUNCATE TABLE wm_storage_area;
TRUNCATE TABLE wm_waste_line;
TRUNCATE TABLE pro_client_order;
TRUNCATE TABLE pro_workorder;
TRUNCATE TABLE wm_issue_line;
TRUNCATE TABLE md_workstation;
TRUNCATE TABLE pro_process;
TRUNCATE TABLE pro_route_product;
TRUNCATE TABLE wm_issue_header;
TRUNCATE TABLE wm_product_recpt;
TRUNCATE TABLE wm_storage_location;
TRUNCATE TABLE wm_item_recpt_line;
TRUNCATE TABLE wm_warehouse;
TRUNCATE TABLE pro_route;
TRUNCATE TABLE wm_item_recpt;
TRUNCATE TABLE wm_product_produce;
TRUNCATE TABLE wm_product_produce_line;
TRUNCATE TABLE wm_product_recpt_line;
TRUNCATE TABLE md_client;
TRUNCATE TABLE md_vendor;
TRUNCATE TABLE md_workshop;
TRUNCATE TABLE md_workstation_machine;
TRUNCATE TABLE wm_product_salse;
TRUNCATE TABLE wm_product_salse_line;

SET FOREIGN_KEY_CHECKS = 1;