# 项目相关配置
t3rik-platform:
  # 名称
  name: t3rik-platform
  # 版本
  version: 0.0.1
  # 版权年份
  copyrightYear: 2022
  # 实例演示开关
  demoEnabled: true
  # 文件路径 示例（ Windows配置D:/t3rik/uploadPath，Linux配置 /home/t3rik/uploadPath）
  profile: D:/source_code/j2eeworkspace/t3rik-mes/upload
  #profile: /home/www/uploadPath
  # 获取ip地址开关
  addressEnabled: false
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # oss配置
  oss:
    end-point: your_address
    buket: your_buket
    access-key: your_key
    secret-key: your_key
    oss-type: minio